version: '3.4'

services:
  30daysofcloudleaderboard:
    image: 30daysofcloudleaderboard
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./database:/app/database
