version: '3.4'

services:
  30daysofcloudleaderboard:
    image: 30daysofcloudleaderboard
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6363:6363"
    volumes:
      - ./database:/app/database
    environment:
      - SECRET_KEY=<SECRET_KEY_FOR_PASSWD>
      - EMAIL_USER=<EMAIL ACC>
      - EMAIL_PASS=<EMAIL_PASSWD>
      - SENDER_EMAIL=<SENDER_EAMIL>
      - SCRAPER_SWITCH=true
      - YEAR=<competition year>
